### Check if user exists
GET http://localhost:5173/api/auth?action=checkUser&mobile=9999999999
Accept: application/json

### Send OTP
POST http://localhost:5173/api/sendOTP
Content-Type: application/json

{
  "mobileNumber": "8888888880",
  "name": "Akshata"
}

### Verify OTP
POST http://localhost:5173/api/verifyOTP
Content-Type: application/json

{
  "uid": "a2501cac-123e-4086-931c-318e3e43eb08",
  "otp": "570295",
   "dataName": "applicant"
}


### Send Email OTP
POST http://localhost:5173/api/sendEmailOTP
Content-Type: application/json

{
  "email": "test@example.com",
  "id": 846,
  "name": "Akshata"
}


### Verify Email OTP
POST http://localhost:5173/api/verifyEmailOTP
Content-Type: application/json

{
  "uid": "f697ff2b-0fdc-48a9-83cd-79665d6d9f1c",
  "otp": "717127",
  "dataName": "applicant"
}





### Register user
POST http://localhost:5173/api/auth
Content-Type: application/json

{
  "action": "register",
  "mobile": "9999999999",
  "name": "Akshata Sangale",
  "password": "Password@123",
  "otp": "955191"
}


### Login user
POST http://localhost:5173/api/auth
Content-Type: application/json

{
  "action": "login",
  "mobile": "8767096290",
  "password": "Admin@123"
}

### Get user by mobile
POST http://localhost:5173/api/auth
Content-Type: application/json

{
  "action": "getUserByMobile",
  "mobile": "9999999999"
}


### Change password
POST http://localhost:5173/api/auth
Content-Type: application/json

{
  "action": "changePassword",
  "mobile": "9999999999",
  "password": "NewPassword@123"
}


##Master DropDown

### Fetch Districts
GET http://localhost:5173/api/masters
Content-Type: application/json


### Get Masters (District + Gender)
GET http://localhost:5173/api/masters
Content-Type: application/json




